### ISSUE TITLE
See ${} when creating solution

### ISSUE THREAD

**Issue by jongio** [Azure/iotedgedev#223]
![image](https://user-images.githubusercontent.com/2163001/43611510-2da7e890-965e-11e8-8206-b787d2ef5e16.png)

=========================================================================================================
======== DOTNET NEW AZIOTEDGEMODULE -N FILTERMODULE -R ${CONTAINER_REGISTRY_SERVER}/FILTERMODULE ========
=========================================================================================================

**Comment by LazarusX** [comment]
This is by design. We will have `"${container_registry_server}/filtermodule"` as repository value in module.json after scaffolding, and the build process will replace the placeholder with active container registry server value in .env. The benefit is that if the user want to update the container registry server, he only needs to update the .env file.

**Comment by LazarusX** [comment]
However, I am reconsidering the adding new module experience as we are going to support multi container registries.

Currently, the solution on top of my mind is:
* Require the user to provide image registry when adding a new module
* Fill module.json with the actual value of image registry
* Update .env to include credential entries for the new image registry
* Update the `registryCredentials` section in deployment.template.json to include references to the registry credential env.

**Comment by jongio** [comment]
Ic.  Thanks.  Closing.
