### ISSUE TITLE
iotedgedev init fails to list Edge devices in IoT Hub

### ISSUE THREAD

**Issue by davekbell** [Azure/iotedgedev#320]
![image](https://user-images.githubusercontent.com/12644541/45670294-6a8aaf00-bb33-11e8-9e7a-11b91bed94af.png)

Steps to Reproduce:

1.  Run iotedgedev init
2.  Follow prompts
3. When it gets to the section "Retreiving Edge Devices in 'your-iot-hub-name-here' - it drops with an error
4. Recreated issue with different subscriptions and hubs

**Comment by LazarusX** [comment]
Based on the error code, looks like you don't have access to list devices in the IoT Hub. What's the behavior on Azure portal?

**Comment by davekbell** [comment]
Portal is fine, it lists the Edge devices:

![image](https://user-images.githubusercontent.com/12644541/45819057-71aceb00-bcf4-11e8-8fe3-0fa4c223f6d6.png)

**Comment by digimaun** [comment]
Couple thoughts I have on this right now.

Like @LazarusX is saying this unauthorized error is coming from the underlying az call (IoT extension). 

This is happening [here](https://github.com/Azure/iotedgedev/blob/master/iotedgedev/azurecli.py#L462) (assuming not much drift between @davekbell version and master). If no explicit connection string is passed in, then the 'iothubowner' policy is used to create the auth token (otherwise the connection string details are used).

First I would validate whether or not running the az command manually (rather than through the iotedgedev layer) works i.e. execute 'az iot hub device-identity list --hub-name <your hub> --edge-enabled'.  You can also test with a connection string for more data points.

Second I can't repro the issue (based on the original repro steps) with a fresh iotedgedev container instance. Couple example ways I can reproduce this error:

- If just providing the iothub name (what iotedgedev is currently doing) remove 'registry read' permissions from 'iothubowner' policy
- If providing connection string (via --login), use a policy that doesn't have registry read permissions (like the default 'service' one)

All this being said, these scenarios to trigger unauthorized errors should not be applicable to a standard iotedgedev init run.

**Comment by LazarusX** [comment]
Close due to inactivity. Please reopen if you can reproduce this issue.
