### ISSUE TITLE
Clarify difference between iotedgedev and iotedgehubdev cli tools

### ISSUE THREAD

**Issue by cicorias** [Azure/iotedgedev#376]
Is there something somewhere that clarifies the difference between these two CLI tools for IoT Edge Development?  

https://github.com/Azure/iotedgehubdev
https://github.com/Azure/iotedgedev

**Comment by shizn** [comment]
IoTEdgeHubDev is a dependency of IoTEdgeDev. 
IoTEdgeHubDev simulates the env for moduleClient, so that you can run moduleClient without IoT Edge security daemon.

IoTEdgeHubDev is also integrated in VS Code IoT Edge tools and VS IoT Edge tools, so that you can create, run and debug modules in VS Code and VS.

**Comment by josiahls** [comment]
What is the difference between this and existing azure tools like:
`az iot edge deployment create`
or
`az iot edge deployment set-modules`
or
`az acr build ` ?

Is this supposed to be an abstraction along with the simulation support? What I am most curious about is whether this would allow me to avoid using VS studio (I'm a jetbrains person). Does VS studio use this CLI for its commands?

**Comment by jongio** [comment]
@shizn for comment as well.

iotedgedev abstracts the commands you mention above to help you build IoT Edge solutions - instead of manually calling each CLI command for each module it bundles them together in single commands.

It would be an interesting exercise to try to create a JetBrains extension based on this CLI.  I personally haven't used JetBrains, but it should be possible.  Is that something you want to try?

VS Code and VS do not call this CLI, but the functionality should behave exactly the same across the CLI and the IDEs.

**Comment by shizn** [comment]
Hi @josiahls,
The simple answer is iotedgedev is a wrapper(or you can say abstraction) for docker CLI and az iot CLI plus simulation support to help IoT Edge developers. So you don't need to manually do everything by yourself. VS Code and VS do not use this CLI but we are keeping feature parity. You can definitely use this CLI for your JetBrains IDE.
